# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 LiveAvatar Contributors
# Commercial use requires a separate written license; see ../LICENSE.

"""REST routes + FastAPI app assembly (audio/video WS live in ws_routes)."""

from __future__ import annotations

import logging
import os
import secrets
from typing import Any

from fastapi import Depends, FastAPI, Request
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field

from .. import __version__
from ..pool import AvatarNotFound, AvatarPoolError
from .auth import Unauthorized, require_api_key
from .encoders import _valid_avatar_id
from .session_manager import (
    _default_avatar_id,
    _ensure_pipeline,
    _lifespan,
    _open_duplex_session,
)
from .state import state

logger = logging.getLogger("liveavatar.publish")


class CreateSessionBody(BaseModel):
    """POST /v1/sessions request body (all fields optional)."""

    session_id: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[A-Za-z0-9_\-]+$",
        description="Client-chosen session id; autogenerated when omitted.",
    )
    avatar_id: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[A-Za-z0-9_\-]+$",
        description="Avatar to lease; defaults to the first available.",
    )
    mode: str = Field(
        default="push",
        pattern=r"^(push|duplex)$",
        description=(
            "'push' (default): client streams TTS-ready PCM through the "
            "avatar adapter. 'duplex': full-duplex star session — the "
            "server runs VAD/EOU/ASR → LLM → TTS → Avatar on mic audio."
        ),
    )


def _mint_session_token(session_id: str) -> str | None:
    """Short-lived per-session token (M-D), or None when not configured."""
    secret = state.settings.api_secret
    if not secret:
        return None
    from .tokens import make_session_token

    return make_session_token(
        api_key=state.settings.api_key,
        api_secret=secret,
        session_id=session_id,
        ttl_s=state.settings.token_ttl_s,
    )


app = FastAPI(title="LiveAvatar", version=__version__, lifespan=_lifespan)


@app.exception_handler(Unauthorized)
async def _unauthorized_handler(
    request: Request, exc: Unauthorized
) -> JSONResponse:
    """Render the auth dependency's failure as the legacy 401 body."""
    return JSONResponse({"error": "unauthorized"}, status_code=401)


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse({"status": "ok"})


@app.get("/metrics")
async def metrics_endpoint(
    request: Request, _auth: None = Depends(require_api_key)
) -> Any:
    """Prometheus exposition (opt-in via LIVEAVATAR_METRICS=on)."""
    from ..observability import (
        _METRICS_CONTENT_TYPE,
        METRICS_ENV,
        metrics_enabled,
        render_metrics,
    )

    if not metrics_enabled():
        return JSONResponse(
            {"error": f"metrics disabled (set {METRICS_ENV}=on)"},
            status_code=404,
        )
    from fastapi.responses import Response

    return Response(render_metrics(state), media_type=_METRICS_CONTENT_TYPE)


@app.get("/v1/avatars")
async def list_avatars(
    request: Request, _auth: None = Depends(require_api_key)
) -> JSONResponse:
    from ..pool import discover_avatars

    avatars = discover_avatars(state.pool_config.avatar_data_root)
    return JSONResponse(
        {
            "data_root": state.pool_config.avatar_data_root,
            "avatars": sorted(avatars.keys()),
        }
    )


@app.post("/v1/sessions")
async def create_session(
    request: Request,
    body: CreateSessionBody | None = None,
    _auth: None = Depends(require_api_key),
) -> JSONResponse:
    """Create a session: acquire the avatar lease and open the video sink.

    Body (all optional): ``{"session_id": "...", "avatar_id": "yongen",
    "mode": "push" | "duplex"}``. When ``LIVEAVATAR_API_SECRET`` is set the
    response also carries a short-lived ``session_token`` for WS handshakes.
    """
    body = body or CreateSessionBody()
    session_id = body.session_id or f"sess_{secrets.token_hex(8)}"
    avatar_id = body.avatar_id or _default_avatar_id()

    # S4: reject unsafe avatar ids before any filesystem use (both modes).
    if not _valid_avatar_id(avatar_id):
        return JSONResponse({"error": "invalid avatar_id"}, status_code=400)

    if body.mode == "duplex":
        duplex_resp = await _open_duplex_session(session_id, avatar_id)
        return _with_session_token(duplex_resp, session_id)

    pipeline = await _ensure_pipeline()

    if len(pipeline.sessions) >= state.settings.max_sessions:
        return JSONResponse(
            {"error": "session limit reached"}, status_code=429
        )

    try:
        await pipeline.open_session(session_id, avatar_id)
    except AvatarNotFound as exc:
        return JSONResponse({"error": str(exc)}, status_code=404)
    except AvatarPoolError as exc:
        return JSONResponse({"error": str(exc)}, status_code=503)

    body_json: dict[str, Any] = {
        "session_id": session_id,
        "avatar_id": avatar_id,
        "mode": "push",
        "transport": "ws",
        "sample_rate": 16000,
        "sample_format": "s16le",
        "video_ws": f"/v1/sessions/{session_id}/video",
    }
    return _with_session_token(JSONResponse(body_json), session_id)


def _with_session_token(resp: JSONResponse, session_id: str) -> JSONResponse:
    """Attach the per-session token to a 2xx session-creation response."""
    token = _mint_session_token(session_id)
    if token is None or not (200 <= resp.status_code < 300):
        return resp
    import json

    raw = bytes(resp.body)  # JSONResponse renders to bytes at construction
    data = json.loads(raw.decode())
    data["session_token"] = token
    resp.body = json.dumps(data).encode()
    return resp


@app.delete("/v1/sessions/{session_id}")
async def delete_session(
    session_id: str, request: Request, _auth: None = Depends(require_api_key)
) -> JSONResponse:
    duplex = state.duplex_sessions.pop(session_id, None)
    if duplex is not None:
        await duplex.stop()
        return JSONResponse({"closed": True})
    pipeline = state.pipeline
    if pipeline is None:
        return JSONResponse({"error": "no session"}, status_code=404)
    ok = await pipeline.close_session(session_id)
    return JSONResponse({"closed": ok}, status_code=200 if ok else 404)


@app.get("/v1/sessions/{session_id}/stats")
async def session_stats(
    session_id: str, request: Request, _auth: None = Depends(require_api_key)
) -> JSONResponse:
    duplex = state.duplex_sessions.get(session_id)
    if duplex is not None:
        return JSONResponse(duplex.stats())
    pipeline = state.pipeline
    if pipeline is None or pipeline.get_session(session_id) is None:
        return JSONResponse({"error": "no session"}, status_code=404)
    return JSONResponse(pipeline.session_stats(session_id))


# ────────────────────────────────────────── static web demo (optional)


@app.get("/")
async def index() -> Any:
    index_html = os.path.join(_web_dir(), "index.html")
    if os.path.exists(index_html):
        return FileResponse(index_html)
    return JSONResponse(
        {"service": "LiveAvatar", "docs": "/docs", "health": "/health"}
    )


def _web_dir() -> str:
    # publish/routes.py → publish/ → liveavatar/ → src/ → repo root/web
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "..", "..", "web"))
