"""REST routes + FastAPI app assembly (audio/video WS live in ws_routes)."""

from __future__ import annotations

import logging
import os
import secrets
from typing import Any

from fastapi import FastAPI, Request
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field

from ..pool import AvatarNotFound, AvatarPoolError
from .encoders import _valid_avatar_id
from .session_manager import (
    _default_avatar_id,
    _ensure_pipeline,
    _join_room,
    _lifespan,
    _open_duplex_session,
)
from .state import state
from .tokens import make_access_token

logger = logging.getLogger("liveavatar.publish")


class CreateSessionBody(BaseModel):
    """POST /v1/sessions request body (all fields optional)."""

    session_id: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[A-Za-z0-9_\-]+$",
        description="Client-chosen session id; autogenerated when omitted.",
    )
    avatar_id: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[A-Za-z0-9_\-]+$",
        description="Avatar to lease; defaults to the first available.",
    )
    mode: str = Field(
        default="push",
        pattern=r"^(push|duplex)$",
        description=(
            "'push' (default): client streams TTS-ready PCM through the "
            "avatar adapter. 'duplex': full-duplex star session — the "
            "server runs VAD/EOU/ASR → LLM → TTS → Avatar on mic audio."
        ),
    )


def _check_auth(request: Request) -> JSONResponse | None:
    """Return a 401 response when the request is not authorized, else None."""
    key = state.settings.api_key
    if not key:
        return None
    if request.headers.get("X-API-Key") == key:
        return None
    return JSONResponse({"error": "unauthorized"}, status_code=401)


def _check_ws_auth(websocket: Any) -> bool:
    """True when the WS handshake is authorized (or auth is disabled)."""
    key = state.settings.api_key
    if not key:
        return True
    provided = websocket.query_params.get("api_key") or websocket.headers.get(
        "x-api-key"
    )
    return provided == key


app = FastAPI(title="LiveAvatar", version="0.1.0", lifespan=_lifespan)


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse({"status": "ok", "livekit": state.settings.livekit_enabled})


@app.get("/metrics")
async def metrics_endpoint(request: Request) -> Any:
    """Prometheus exposition (opt-in via LIVEAVATAR_METRICS=on)."""
    unauthorized = _check_auth(request)
    if unauthorized is not None:
        return unauthorized
    from ..observability import (
        _METRICS_CONTENT_TYPE,
        METRICS_ENV,
        metrics_enabled,
        render_metrics,
    )

    if not metrics_enabled():
        return JSONResponse(
            {"error": f"metrics disabled (set {METRICS_ENV}=on)"},
            status_code=404,
        )
    from fastapi.responses import Response

    return Response(render_metrics(state), media_type=_METRICS_CONTENT_TYPE)


@app.get("/v1/avatars")
async def list_avatars(request: Request) -> JSONResponse:
    unauthorized = _check_auth(request)
    if unauthorized is not None:
        return unauthorized
    from ..pool import discover_avatars

    avatars = discover_avatars(state.pool_config.avatar_data_root)
    return JSONResponse(
        {
            "data_root": state.pool_config.avatar_data_root,
            "avatars": sorted(avatars.keys()),
        }
    )


@app.post("/v1/sessions")
async def create_session(
    request: Request, body: CreateSessionBody | None = None
) -> JSONResponse:
    """Create a session: acquire the avatar lease and join the room.

    Body (all optional): ``{"session_id": "...", "avatar_id": "yongen",
    "mode": "push" | "duplex"}``.
    """
    unauthorized = _check_auth(request)
    if unauthorized is not None:
        return unauthorized
    body = body or CreateSessionBody()
    session_id = body.session_id or f"sess_{secrets.token_hex(8)}"
    avatar_id = body.avatar_id or _default_avatar_id()

    # S4: reject unsafe avatar ids before any filesystem use (both modes).
    if not _valid_avatar_id(avatar_id):
        return JSONResponse({"error": "invalid avatar_id"}, status_code=400)

    if body.mode == "duplex":
        return await _open_duplex_session(session_id, avatar_id)

    pipeline = await _ensure_pipeline()

    if len(pipeline.sessions) >= state.settings.max_sessions:
        return JSONResponse(
            {"error": "session limit reached"}, status_code=429
        )

    # Transport selection: "livekit" joins the room as a publisher bot;
    # "ws" (default) leaves publisher creation to the service factory,
    # which installs a WebSocketSink served at /v1/sessions/{sid}/video.
    use_livekit = False
    room = participant = None
    if state.settings.transport == "livekit":
        if not state.settings.livekit_enabled:
            return JSONResponse(
                {
                    "error": "transport=livekit requires LIVEKIT_URL, "
                    "LIVEKIT_API_KEY and LIVEKIT_API_SECRET"
                },
                status_code=503,
            )
        try:
            room, participant = await _join_room(session_id)
        except RuntimeError as exc:  # livekit SDK missing
            return JSONResponse({"error": str(exc)}, status_code=503)
        use_livekit = True

    try:
        await pipeline.open_session(
            session_id,
            avatar_id,
            local_participant=participant,
            room=room,
        )
    except AvatarNotFound as exc:
        if room is not None:
            await room.disconnect()
        return JSONResponse({"error": str(exc)}, status_code=404)
    except AvatarPoolError as exc:
        if room is not None:
            await room.disconnect()
        return JSONResponse({"error": str(exc)}, status_code=503)

    resp: dict[str, Any] = {
        "session_id": session_id,
        "avatar_id": avatar_id,
        "mode": "push",
        "transport": state.settings.transport,
        "livekit": use_livekit,
        "sample_rate": 16000,
        "sample_format": "s16le",
        "video_ws": f"/v1/sessions/{session_id}/video",
    }
    if use_livekit:
        resp["url"] = (
            state.settings.public_livekit_url or state.settings.livekit_url
        )
        resp["room"] = state.settings.livekit_room
        # Browser token: subscribe-only (no publish / data channels).
        resp["token"] = make_access_token(
            api_key=state.settings.livekit_api_key,
            api_secret=state.settings.livekit_api_secret,
            identity=session_id,
            room=state.settings.livekit_room,
            can_publish=False,
        )
    return JSONResponse(resp)


@app.delete("/v1/sessions/{session_id}")
async def delete_session(session_id: str, request: Request) -> JSONResponse:
    unauthorized = _check_auth(request)
    if unauthorized is not None:
        return unauthorized
    duplex = state.duplex_sessions.pop(session_id, None)
    if duplex is not None:
        await duplex.stop()
        return JSONResponse({"closed": True})
    pipeline = state.pipeline
    if pipeline is None:
        return JSONResponse({"error": "no session"}, status_code=404)
    ok = await pipeline.close_session(session_id)
    return JSONResponse({"closed": ok}, status_code=200 if ok else 404)


@app.get("/v1/sessions/{session_id}/stats")
async def session_stats(session_id: str, request: Request) -> JSONResponse:
    unauthorized = _check_auth(request)
    if unauthorized is not None:
        return unauthorized
    duplex = state.duplex_sessions.get(session_id)
    if duplex is not None:
        return JSONResponse(duplex.stats())
    pipeline = state.pipeline
    if pipeline is None or pipeline.get_session(session_id) is None:
        return JSONResponse({"error": "no session"}, status_code=404)
    return JSONResponse(pipeline.session_stats(session_id))


# ────────────────────────────────────────── static web demo (optional)


@app.get("/")
async def index() -> Any:
    index_html = os.path.join(_web_dir(), "index.html")
    if os.path.exists(index_html):
        return FileResponse(index_html)
    return JSONResponse(
        {"service": "LiveAvatar", "docs": "/docs", "health": "/health"}
    )


def _web_dir() -> str:
    # publish/routes.py → publish/ → liveavatar/ → src/ → repo root/web
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "..", "..", "web"))
